apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-nb5v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-nb5v
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-nb5v
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-nb5v
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-nb5v
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rsyb-tenant/rhtap-demo-app/hacbs-test-project-nb5v@sha256:80a4dae4dddf403d786939b3112d0b5bed52c244d4abc8276b4ec70bb456da77
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
