apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-nb5v
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rsyb-tenant/rhtap-demo-app/hacbs-test-project-nb5v@sha256:b5d9732a689d0818711685a546a2987f82fae1411eaf982fd52288aa0c5c64ae
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
